title : Laksmi Anindyati
logo : assets/img/gambar.jpeg
description : Lecturer and Researcher @ Politeknik Kelapa sawit Citra Widya Edukasi https://poltekcwe.ac.id/
#show_download : false
theme: jekyll-theme-minimal
